config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "about", to: "about#index"
  
  get "signup", to: "registrations#new"
  post "signup", to: "registrations#create"
  
  get "signin", to: "sessions#new"
  post "signin", to: "sessions#create"
  
  
  get "menu", to: "orders#new"
  get "Breakfast", to: "orders#bf"
  get "Lunch", to: "orders#lunch"
  get "Dinner", to: "orders#dinner"
  get "owner", to: "odash#onew"
  
  delete "logout", to: "sessions#destroy"
  
  root to:"main#index"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/food.rb
class Food < ActiveRecord::Base
    has_many :orderitems
    has_many :orders
    #belongs_to :orderitem
end

app/models/order.rb
class Order < ActiveRecord::Base
    belongs_to :user
    has_many :foods
end

app/models/orderitem.rb
class Orderitem < ApllicationRecord

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be valid mailid"}

    def owner?
        user_type == 1
    end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user
    def set_current_user
        if session[:user_id]
          Current.user = User.find_by(id: session[:user_id])
        end
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
      if session[:user_id]
        @user = User.find(session[:user_id])
        redirect_to menu_path
      end        
      #if params[:user_type] == 1
        
      


      
    end
  end
  

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def new
        @order = Order.new
      end
    def create
        @order = Order.new#(order_params)
        
    
        respond_to do |formart|
          if @order.save
            format.html { redirect_to order_path, notice: 'Order was successfully created.' }
            
          else
            format.html { render :new }
            
          end
        end
      end
    
    
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Sucessfully created account"
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create
        user = User.find_by(email: params[:email])
        #user.owner?
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            # if user_type == 0
                if user.owner? 
                    redirect_to owner_path, notice: "Logged in successfully"
                    
                else
                    redirect_to menu_path, notice: "Logged in successfully"
                    
                        
                end            
        else
            flash[:alert] = "Ivalid email or password"
            render :new
        end 
    end
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/about.html.erb
<h1>AboutUs</h1>

app/views/about/index.html.erb
<!-- About Container -->
<div class="w3-container w3-padding-64 w3-red w3-grayscale w3-xlarge" id="about">
  <div class="w3-content">
    <h1 class="w3-center w3-jumbo" style="margin-bottom:64px">About Us</h1>
    <p>We welcome you to sit back, unwind and appreciate the lovely sights and hints of the ocean while our best gourmet expert sets you up a scrumptious dinner utilizing the best and freshest ingredients.’Company Name’s legacy comes from The parent  Restaurant which was built up in 1963.
    Delicious’ was worked for people in general and has advanced into a combination between exquisite chic and contemporary fine charge.
    Enjoy our dazzling dishes and make the most of your eating background with us!</p>
    <p><strong>The Chef?</strong> Mr. Italiano himself</p>
    <p>We are proud of our interiors.</p>
    <h1><b>Opening Hours</b></h1>
    
    <div class="w3-row">
      <div class="w3-col s6">
        <p>Monday 9:00 - </p>
        <p>Wednesday 10.00 - 24.00</p>
        <p>Thursday 10:00 - 24:00</p>
      </div>
      <div class="w3-col s6">
        <p>Friday 10:00 - 12:00</p>
        <p>Saturday 10:00 - 23:00</p>
        <p>Sunday 7:00 - 23:00</p>
      </div>
    </div>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ymp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if session[:user_id] %>
    <%= render partial: "orders/new" %>
  <% else %>
    <%= render partial: "shared/navbar" %>
  <% end %>
  <div class="container">
    <%= render partial: "shared/flash" %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex alig-items-center justify-content-center" <h1="" "welcome="" to="" delicous="" catering"="" style="font-size=3rem">

    <% if @user&.owner? %>
        <h1>I AM THE OWNER !!! </h1>
        <% else %>
            <h1>WELCOME CUSTOMER </h1>
            
 <% end %>
</div>

app/views/odash/onew.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="navbar">DASHBOARD</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="signup" href="pendingorders">PENDING ORDERS</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="completedorders">COMPLETED ORDERS</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="allorderss">ALL ORDERS</a>
        </li>
      </ul>
    
   
    
    </div>
  </div>
</nav>

app/views/orders/_new.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="navbar">MENU</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="signup" href="Breakfast">BREAKFAST</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="Lunch">LUNCH</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="Dinner">DINNER</a>
        </li>
      </ul>
    
   
    
    </div>
  </div>
</nav>

app/views/orders/bf.html.erb
<html>
<style>
	p{color: green;}
</style>
<body>
<h1> BREAK FAST	</h1>
<div>
<p>PLAIN IDLY<span>RS.20</span><input type="number" name="price" /></p>
<p>PODI IDLY<span>RS.30</span><input type="number" name="price" /></p>
<p>PLAN DOSA<span>RS.50</span><input type="number" name="price" /></p>
<p>ONION DOSA<span>RS.60</span><input type="number" name="price" /></p>
<p>MASALA DOSA<span>RS.60</span><input type="number" name="price" /></p>
<p>PURI<span>RS.10</span><input type="number" name="price" /></p>
<p>VADA<span>RS.10</span><input type="number" name="price" /></p>

</div>

</html>

app/views/orders/dinner.html.erb
<style>
	p{color: darkblue;}
</style>
<body>
<h1> DINNER	</h1>
<div>
<p>PLAIN IDLY<span>RS.20</span><input type="number" name="price" /></p>
<p>PODI IDLY<span>RS.30</span><input type="number" name="price" /></p>
<p>GHEE ROAST<span>RS.50</span><input type="number" name="price" /></p>
<p>EGG NOODLES<span>RS.50</span><input type="number" name="price" /></p>
<p>VEG NOODLES<span>RS.50</span><input type="number" name="price" /></p>
<p>CHICKEN NOODLES<span>RS.70</span><input type="number" name="price" /></p>
<p>MANCHURIYA<span>RS.50</span><input type="number" name="price" /></p>
</div>
<button type="submit" value="Submit">SAVE</button>

app/views/orders/lunch.html.erb
<html>
<style>
	p{color: black;}
</style>
<body>
<h1> LUNCH </h1>
<div>
<p>MEALS<span>RS.100</span><input type="number" name="price" /></p>
<p>CHICKEN BIRIYANI<span>RS.150</span><input type="number" name="price" /></p>
<p>CHILLY CHICKEN<span>RS.250</span><input type="number" name="price" /></p>
<p>MUTTON BIRIYANI<span>RS.300</span><input type="number" name="price" /></p>
<p>FISH BIRIYANI<span>RS.250</span><input type="number" name="price" /></p>
<p>CHICKEN CURRY<span>RS.100</span><input type="number" name="price" /></p>
<p>MUTTON CURRY<span>RS.100</span><input type="number" name="price" /></p>

</div>

</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>

    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>
<% if flash[:alert] %>
<div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="navbar">DELICIOUS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="signup" href="signup">SIGNUP</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="signin">SIGNIN</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="about">ABOUT</a>
        </li>
      </ul>
      <ul class="navbar-av ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
        <li class="nav-item"
          <span><%= Current.user.email %></span> 
        </li>
        <li class="nav-item">
          <%= button_to "Logout", logout_path, method: :delete %>
        </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", signup_path %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", signin_path %>
          </li>
          <% end %>
      </ul>
   
    
    </div>
  </div>
</nav>